<?php

/**
 * Path configuration for directories and files.
 *
 * Use absolute paths in these variables.
 */

$reel_source_path = '../../Hale Microfilm'; // /path/to/directory containing 'Hale Reel#nnn' directories
$bag_destination_path = '../../bagit'; // /path/to/destination where output directory will be created
$islandora_url = 'https://hale.archives.caltech.edu'; // no trailing slash
$collection_id = 'HaleGE';
$source_organization = 'Caltech Archives';
$contact_name = 'Peter Collopy';
$contact_email = 'pcollopy@caltech.edu';

$processes = ''; // for use when calculating checksums in bagit
