<?php

/**
 * Path configuration for directories and files.
 *
 * Use absolute paths in these variables.
 */

// the file containing an index of box ranges
// (`/path/to/scripts/boxes-10000.csv`)
$boxes_csv = '';
// the file with the series/box/folder and reel/file data
// (`/path/to/csv/hale.csv`)
$csv_source_file = '';
// the directory for processed object directories
// (`/path/to/Archives/Workspace/Hale`)
$destination_parent = '';
// the path where the reel directories are located
// (`/path/to/Archives/Hale Microfilm`)
$reel_source_path = '';
