<?php

/**
 * Path configuration for directories and files.
 *
 * Use absolute paths in these variables.
 */

// the file containing an index of box ranges
// (`/path/to/csv/index.csv`)
$index_csv = '';
// the file with the series/box/folder and reel/file data
// (`/path/to/csv/hale.csv`)
$source_csv = '';
// the directory for processed object directories
// (`/path/to/Workspace/Hale`)
$destination_parent = '';
// the path where the reel directories are located
// (`/path/to/Archives/Hale Microfilm`)
$reel_source_path = '';
